# Generated by Django 6.0.2 on 2026-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading (can use line breaks with \\n)', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Sub-text under heading', max_length=200)),
                ('image', models.ImageField(help_text='Background image (recommended 1400x500px)', upload_to='banners/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/', help_text='URL for the CTA button', max_length=200)),
                ('badge_text', models.CharField(blank=True, default='Sale', help_text='Small pill label above title', max_length=40)),
                ('badge_color', models.CharField(choices=[('orange', 'Orange'), ('pink', 'Pink'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('purple', 'Purple')], default='orange', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first in carousel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
